FROM node:14-alpine

WORKDIR '/app'

COPY ./package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

# PowerShell command
# C:\work\webdevelop\docker\frontend
# docker run -it -p 3000:3000 -v /app/node_modules -v /c/work/webdevelop/docker/frontend:/app -e CHOKIDAR_USEPOLLING=true guomingyuan/frontend